### ISSUE TITLE
[AVM Module Issue]: problem with provider pinning for `azure/azapi`

### ISSUE THREAD

**Issue by JensKruseAvanade** [Azure/terraform-azurerm-avm-ptn-policyassignment#65]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

2.1

### Description

`Terraform init`

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider azure/azapi:
│ no available releases match the given constraints >= 1.14.0, ~> 1.14, ~>
│ 2.0, < 3.0.0
```

My assumption is, that there is a typo in the provider requirements for "Azure/azapi" (instead of "azure/azapi" (see terraform-azurerm-avm-ptn-policyassignment/terraform.tf, line 5).

**Comment by JensKruseAvanade** [comment]
@bjornhofer Sorry to bother you: any update on this? How can I support?

**Comment by bjornhofer** [comment]
@JensKruseAvanade Hi, no problem I'm currently a bit in a rush with other things - but I plan to solve it at latest on the upcoming Friday.

**Comment by bjornhofer** [comment]
Hello @JensKruseAvanade 

I could not reproduce your issue in my test environment. (see: [https://ibb.co/YBXwqRr](screenshot)

Can you provide me more details (Terraform version, operating system, ...)


Thanks in advance

Björn

**Comment by JensKruseAvanade** [comment]
Hi @bjornhofer 
Thanks for your answer.
This is my github action environment:
```yml
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
[...]
      # Install the preferred version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9
```
HTH,
Jens
